apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-registries
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: ["team-*", "app-*"]
      validate:
        message: "Images must be sourced from approved ECR registries only."
        pattern:
          spec:
            containers:
              - image: "*.dkr.ecr.*.amazonaws.com/*"
            =(initContainers):
              - image: "*.dkr.ecr.*.amazonaws.com/*"
